[build]
publish = "dist"
command = "npm run build"

[functions]
directory = "netlify/functions"

[[edge_functions]]
function = "prerender"
path = "/*"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
